remote_theme: pages-themes/time-machine@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Shaik Mohammed Sameer
description: Hi there! I'm Shaik Mohammed Sameer, a passionate Data Analyst with a strong foundation in statistics, machine learning, and data storytelling. I love turning raw data into actionable insights and building models that solve real-world problems.

