title: Minimal theme
logo: /assets/img/logo.png
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal # add this line to the plugins list if you already have one
title: Shaik Mohammed Sameer
description: Hi there! I'm Shaik Mohammed Sameer, a passionate Data Analyst with a strong foundation in statistics, machine learning, and data storytelling. I love turning raw data into actionable insights and building models that solve real-world problems.

